version: "3.9"

x-app: &app
  image: ghcr.io/wassef911/showme:main-latest
  restart: always
  env_file:
    - AZURE_BLOB_CONNECTION_STRING
    - SHOWME_HOST
    - SHOWME_DB_FILE
    - SHOWME_REDIS_HOST
    - TESTKAFKA_KAFKA_BOOTSTRAP_SERVERS

services:
  api:
    <<: *app
    command: /opt/app/entrypoint.sh
    ports:
      - "80:80"

  worker:
    <<: *app
    command:
      - taskiq
      - worker
      - showme.tkq:broker

  redis:
    image: bitnami/redis:6.2.5
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  zookeeper:
    image: "bitnami/zookeeper:3.7.1"
    hostname: "showme-zookeeper"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_LEVEL: "ERROR"

  kafka:
    image: "bitnami/kafka:3.2.0"
    hostname: "showme-kafka"
    environment:
      KAFKA_BROKER_ID: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://showme-kafka:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "showme-zookeeper:2181"
