version: "3.9"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  depends_on:
    redis:
      condition: service_healthy
    kafka:
      condition: service_healthy
  environment:
    - AZURE_BLOB_CONNECTION_STRING
    - SHOWME_HOST
    - SHOWME_DB_FILE
    - SHOWME_REDIS_HOST
    - TESTKAFKA_KAFKA_BOOTSTRAP_SERVERS

services:
  api:
    <<: *app
    command: /opt/app/entrypoint.sh
    ports:
      - "80:8000"

  worker:
    <<: *app
    command:
      - taskiq
      - worker
      - showme.tkq:broker
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1G

  redis:
    image: bitnami/redis:6.2.5
    restart: unless-stopped
    expose:
      - 6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G

  zookeeper:
    image: "bitnami/zookeeper:3.7.1"
    restart: unless-stopped
    expose:
      - 2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_LEVEL: "ERROR"
    healthcheck:
      test: zkServer.sh status
      interval: 1s
      timeout: 3s
      retries: 30

  kafka:
    image: "bitnami/kafka:3.2.0"
    restart: unless-stopped
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 1s
      timeout: 3s
      retries: 30
    depends_on:
      zookeeper:
        condition: service_healthy