name: Testing showme

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    services:
      showme-zookeeper:
        image: "bitnami/zookeeper:3.7.1"
        env:
          ALLOW_ANONYMOUS_LOGIN: "yes"
          ZOO_LOG_LEVEL: "ERROR"
        options: >-
          --health-cmd="zkServer.sh status"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=8

      showme-kafka:
        image: bitnami/kafka:3.2.0
        env:
          KAFKA_BROKER_ID: "1"
          ALLOW_PLAINTEXT_LISTENER: "yes"
          KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
          KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
          KAFKA_CFG_ZOOKEEPER_CONNECT: "showme-zookeeper:2181"
        options: >-
          --health-cmd="kafka-topics.sh --list --bootstrap-server localhost:9092"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=8
        ports:
        - 9092:9092
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install deps
      run: python3 -m pip install -r requirements-dev.txt

    - name: Run pytest check
      run: python3 -m pytest -vv --cov="showme" .
      env:
        SHOWME_HOST: "0.0.0.0"
        SHOWME_KAFKA_BOOTSTRAP_SERVERS: '["localhost:9092"]'

  push_to_registry:
    needs: pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract branch name
      id: branch_name
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/wassef911/showme:${{ env.BRANCH_NAME }}-latest
